# Generated by Django 4.2.30 on 2026-06-04 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenador',
            name='departamento',
        ),
    ]
