# Generated by Django 4.2.30 on 2026-06-07 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_aluno_coeficiente_rendimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='matriculado_estagio',
            field=models.BooleanField(default=False, help_text='Indica se o aluno está formalmente matriculado em estágio'),
        ),
    ]
