# Generated by Django 4.2.30 on 2026-06-09 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_aluno_matriculado_estagio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('aluno', 'Aluno'), ('coordenador', 'Coordenador'), ('supervisor_empresa', 'Supervisor de Empresa'), ('secretaria', 'Secretaria'), ('casa', 'CASA'), ('reitor', 'Reitor'), ('pro_reitor', 'Pró-Reitor'), ('carreiras', 'Carreiras')], default='aluno', max_length=20),
        ),
    ]
