# Generated by Django 4.2.30 on 2026-06-09 20:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_roles_administrativos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvaliacaoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comentario', models.TextField(blank=True, default='')),
                ('anonimo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes_empresas', to='app.aluno')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacoes', to='app.empresaconcedente')),
                ('processo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='avaliacao_empresa', to='app.processoestagio')),
            ],
            options={
                'verbose_name': 'Avaliação de Empresa',
                'verbose_name_plural': 'Avaliações de Empresas',
            },
        ),
        migrations.AddConstraint(
            model_name='avaliacaoempresa',
            constraint=models.UniqueConstraint(fields=('processo',), name='unique_avaliacao_por_processo'),
        ),
    ]
