# Generated by Django 4.2.30 on 2026-06-09 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_historico_status_processo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, default='')),
                ('arquivo', models.FileField(upload_to='templates-documentos/')),
                ('tipo', models.CharField(choices=[('TCE', 'Termo de Compromisso de Estágio'), ('RELATORIO', 'Relatório'), ('AVALIACAO', 'Avaliação'), ('OUTRO', 'Outro')], default='OUTRO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='templates_documentos', to='app.curso')),
            ],
            options={
                'verbose_name': 'Template de Documento',
                'verbose_name_plural': 'Templates de Documentos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
