# Generated by Django 4.2.30 on 2026-06-10 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_curso_coordenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentoprocesso',
            name='titulo',
            field=models.CharField(blank=True, help_text='Título livre do documento (ex: "Carta de apresentação", "Apólice 2026").', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='documentoprocesso',
            name='tipo',
            field=models.CharField(choices=[('TCE', 'Termo de Compromisso de Estágio'), ('APOLICE', 'Apólice de Seguro'), ('RELATORIO_PARCIAL', 'Relatório Parcial'), ('RELATORIO_FINAL', 'Relatório Final'), ('AVALIACAO_EMPRESA', 'Avaliação da Empresa'), ('TERMO_REALIZACAO', 'Termo de Realização'), ('OUTRO', 'Outro')], default='OUTRO', max_length=30),
        ),
    ]
