# Generated by Django 4.2.30 on 2026-06-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_avaliacaoempresa_aluno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='avaliacaoempresa',
            name='aluno_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256(aluno_pk:empresa_pk:SECRET_KEY) — controle de unicidade sem expor identidade', max_length=64),
        ),
    ]
